baseurl = "http://vincent.demeester.fr"
title = "Vincent Demeester"
theme = "vdf.new"
#pygmentsstyle = "emacs"
pygmentsCodeFences = "true"
pygmentsUseClasses = "true"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "Vincent Demeester"
