baseurl = "http://vincent.demeester.fr"
languageCode = "fr-fr"
title = "Vincent Demeester"
theme = "vdf.new"
pygmentsstyle = "emacs"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "Vincent Demeester"
