baseurl = "http://vincent.demeester.fr"
languageCode = "fr-fr"
title = "Vincent Demeester"
theme = "vdf"
author = "Vincent Demeester"
pygmentsstyle = "emacs"

[taxonomies]
  tag = "tags"
  category = "categories"
